inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/*"
    - "config/environments/production.rb"
    - "db/migrate/*"
    - "db/schema.rb"

Style/Documentation:
  Enabled: false
